spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '{cipher}AQCFG8GYOJZPfa84EK91e4P9l2DDTqcuIRW354B9SiH/DZ4AsRVrPPGg9y6WTcb7YPGLgB94/EBJ1/uPpM2IR0Al/wSwC/IpMzhbeFZsda1tUNUAofvhdPF2ozwoLAXxA23SUqebRkXA1xTSj4UyjSij7EpPD2Y+3P6z8vQBg57nh0rmbcoXt1ntSmsjdNwaDybt3ASxbEXepiX3LjsiJmU3zGnuqAEYAb7eW+kMrR3PzmAkebGZTQYhjFKZvl6sXMzxaexbzVAzgJRIcpzv2o1TMWYRJtpyQ1xbwIQHPYGhX5BSnMdkXgVwmg74sTYmRpsrFP/sOMEUUZT02XjclwLzTH1OTY+3PaCSNTLDlrICyXk+qBXABNedSv6dwiR1fM0='

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 2
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
