spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

server:
  port: 8083

#yoke.notify.url: http://localhost:8082/event/
yoke.notify.url: http://notify-service/event/
